"""
Generate case-specific Claude Desktop project instructions.

Takes a case_id, looks up the case details from Supabase, and outputs
a ready-to-paste project instructions file with all template variables filled in.

Usage:
    python generate_project_instructions.py --case-id <uuid>
    python generate_project_instructions.py --case-id <uuid> --output instructions.md
"""

import argparse
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
load_dotenv(PROJECT_ROOT / ".env")

from supabase import create_client

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

TEMPLATE_PATH = (
    Path(__file__).resolve().parent.parent
    / "04_AGENTIC_ARCHITECTURE"
    / "project_instructions"
    / "case_project_template.md"
)


def main():
    parser = argparse.ArgumentParser(description="Generate Claude Desktop project instructions")
    parser.add_argument("--case-id", required=True, help="Case UUID")
    parser.add_argument("--output", help="Output file path (default: stdout)")
    args = parser.parse_args()

    supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

    # Look up case
    case = supabase.table("cases").select("*").eq("id", args.case_id).single().execute()
    if not case.data:
        print(f"ERROR: Case {args.case_id} not found", file=sys.stderr)
        sys.exit(1)

    c = case.data
    case_id = c["id"]
    firm_id = c.get("firm_id", "00000000-0000-4000-a000-000000000001")

    # Read template
    template = TEMPLATE_PATH.read_text(encoding="utf-8")

    # Replace template variables
    output = template.replace("{{CASE_ID}}", case_id)
    output = output.replace("{{FIRM_ID}}", firm_id)

    # Add case-specific context block at the top
    context_block = f"""<!--
  Auto-generated project instructions for: {c['case_name']}
  Case ID: {case_id}
  Generated by: generate_project_instructions.py
-->

> **Case:** {c['case_name']}
> **Our Client:** {c.get('our_client') or 'Not set'}
> **Opposing Party:** {c.get('opposing_party') or 'Not set'}
> **Party Role:** {c.get('party_role') or 'Not set'}
> **Court:** {c.get('court_name') or 'Not set'}
> **Stage:** {c.get('case_stage') or 'filing'}
> **Status:** {c.get('status') or 'active'}

"""

    # Insert context block after the first heading
    lines = output.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("# Case Project Instructions"):
            lines.insert(i + 1, "\n" + context_block)
            break
    output = "\n".join(lines)

    # Count existing documents
    docs = supabase.table("documents").select("id", count="exact").eq(
        "case_id", case_id
    ).execute()
    doc_count = docs.count or 0

    if doc_count > 0:
        output += f"\n\n---\n\n> **Note:** This case already has {doc_count} documents in the system.\n"

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"Written to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
