import sys
import os
import fitz  # PyMuPDF
import uuid
import pandas as pd
import ast

def extract_images(pdf_path):
    # Only try to extract if it's a PDF
    if not pdf_path.lower().endswith('.pdf'):
        print("SUCCESS: 03_image_extraction.py ran successfully. Number of images extracted: 0 (Not a PDF)")
        return

    # Setup Dynamic Paths
    backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    temp_chunks_dir = os.path.join(backend_dir, 'zz_temp_chunks')
    images_dir = os.path.join(backend_dir, 'data_storage', 'info', 'images')
    os.makedirs(images_dir, exist_ok=True)
    
    # Find the CSV structure report generated by Step 02
    base_name = os.path.splitext(os.path.basename(pdf_path))[0]
    csv_path = os.path.join(temp_chunks_dir, f"{base_name}_structure_report.csv")
    
    if not os.path.exists(csv_path):
        print(f"     ⚠️ No structure report found at {csv_path}. Run 02_doc_detection first.")
        return
        
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"     ⚠️ Error reading structure report: {e}")
        return
    
    # Safely parse the 'image_regions' column from the CSV
    image_regions = []
    if 'image_regions' in df.columns and pd.notna(df['image_regions'][0]):
        try:
            val = df['image_regions'][0]
            # Convert the string representation of the list back into a Python list
            image_regions = ast.literal_eval(val) if isinstance(val, str) else val
        except Exception:
            image_regions = []
    
    # If no images were flagged by the detector, exit cleanly
    if not image_regions:
        print("SUCCESS: 03_image_extraction.py ran successfully. Number of images extracted: 0")
        return

    # --- EXTRACTION PROCESS ---
    try:
        doc = fitz.open(pdf_path)
        extracted_count = 0
        
        for img in image_regions:
            page_num = img.get('page')
            xref = img.get('xref')
            
            if not page_num or not xref:
                continue
                
            # PyMuPDF uses 0-based page indexing
            page = doc[page_num - 1]
            pix = fitz.Pixmap(doc, xref)
            
            # Determine image extension based on colorspace
            if pix.n < 5:
                ext = '.png'
            else:
                ext = '.jpg'
                
            # Generate a unique filename and save
            unique_name = f"img_{base_name}_p{page_num}_{uuid.uuid4().hex[:6]}{ext}"
            img_path = os.path.join(images_dir, unique_name)
            
            pix.save(img_path)
            extracted_count += 1
            pix = None # Clear memory
            
        doc.close()
        print(f"SUCCESS: 03_image_extraction.py ran successfully. Number of images extracted: {extracted_count}")
        
    except Exception as e:
        print(f"ERROR: Failed to extract images: {str(e)}")


if __name__ == '__main__':
    # Make sure it accepts the file path argument from main.py
    if len(sys.argv) != 2:
        print('Usage: python 03_image_extraction.py <file_path>')
        sys.exit(1)
        
    file_path = sys.argv[1]
    extract_images(file_path)